/*
* generated by Xtext
*/
package org.eclipse.gef4.zest.internal.dot.parser.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
public class DotProposalProvider extends org.eclipse.gef4.zest.internal.dot.parser.ui.contentassist.AbstractDotProposalProvider {

}
