/*
 * generated by Xtext
 */
package org.eclipse.gef4.zest.internal.dot.parser.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DotUiModule extends org.eclipse.gef4.zest.internal.dot.parser.ui.AbstractDotUiModule {
	public DotUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
